# .air.toml
[build]
  cmd = "go build -o ./src/core/cmd/tmp/main ./src/core/cmd/main.go"
  bin = "./src/core/cmd/tmp/main"
  tmp_dir = "./src/core/cmd/tmp"

[watch]
  includes = ["./src/**/*.go"]
  excludes = ["./src/core/app/tmp"]

[log]
  level = "info"

[color]
  main = "cyan"
  watcher = "magenta"
  build = "yellow"
  app = "green"