version: "3.8"
volumes:
  sql:
services:
  mysql:
    build: 
      context: .
      dockerfile: ./.docker/Dockerfile
    restart: always    
    ports:
      - "9999:3306"
    volumes:
      - sql:/var/lib/mysql
      - ./.docker/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=${TZ}