version: "3.8"

volumes:
  sql:

services:
  app:
    image: curriculum
    build:
      context: .
      dockerfile: .docker/app.Dockerfile
    container_name: my_app_server
    ports:
      - "8080:8080"
    volumes:
      - .:/app 
    environment:
      - TZ=Asia/Tokyo
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_NAME=sql
      - APP_PORT=8080
      - TEST_DB_USER=user_test
      - TEST_DB_PASSWORD=password_test
      - TEST_DB_HOST=mysql_test
      - TEST_DB_PORT=3306
      - TEST_DB_NAME=sql_test
  mysql:
    build: 
      context: .
      dockerfile: .docker/mysql.Dockerfile
    restart: always    
    ports:
      - "9999:3306"
    volumes:
      - sql:/var/lib/mysql
      - ./.docker/my.cnf:/etc/mysql/my.cnf
    environment:
      - MYSQL_DATABASE=sql
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Tokyo
  mysql_test:
    build: 
      context: .
      dockerfile: .docker/mysql.Dockerfile
    restart: always    
    ports:
      - "9998:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_DATABASE=sql_test
      - MYSQL_USER=user_test
      - MYSQL_PASSWORD=password_test
      - MYSQL_ROOT_PASSWORD=password_test
      - TZ=Asia/Tokyo