@startuml curriculum
allowmixing
hide circle
skinparam linetype ortho

mix_actor プロデューサー
mix_actor ユーザ

package DomainModel {

card 必須項目[
    必須項目
    ==
    メールアドレス : ２５５文字以内
    --
    パスワード : １２文字以上　英数字　各１文字以上
    --
    スキル：
    ①　タグ名（選択式）
    ②　評価（選択式）
    ③　１つ以上（選択式）
    ④　年数　0以上のint型　(5年まで)
]
card 任意項目[
    任意項目
    ==
    自己紹介　：2000文字以内
    --
    経歴：
        詳細    ：1000字以内
        西暦from：1970年以上のint型
        西暦to  ：1970年以上のint型、西暦fromよりも大きい数字
]



    class メールパスログイン
    class ユーザ更新
    class ユーザ新規作成


    メールパスログイン --> ユーザ更新
    メールパスログイン --> ユーザ新規作成
    ユーザ新規作成 --> 必須項目
    ユーザ新規作成 --> 任意項目
   
}
@enduml