-- MySQL Script generated by MySQL Workbench
-- Thu Oct 19 10:16:04 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sql_test
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sql_test
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sql_test` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sql_test` ;

-- -----------------------------------------------------
-- Table `sql_test`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql_test`.`users` (
  `id` CHAR(36) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `profile` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sql_test`.`careers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql_test`.`careers` (
  `id` CHAR(36) NOT NULL,
  `detail` VARCHAR(1000) NOT NULL,
  `ad_from` DATE NOT NULL,
  `ad_to` DATE NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_users_careers_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `fk_users_careers`
    FOREIGN KEY (`user_id`)
    REFERENCES `sql_test`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sql_test`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql_test`.`categories` (
  `id` CHAR(36) NOT NULL,
  `name` VARCHAR(25) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sql_test`.`plans`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql_test`.`plans` (
  `id` CHAR(36) NOT NULL,
  `title` VARCHAR(512) NOT NULL,
  `category_id` CHAR(36) NOT NULL,
  `content` VARCHAR(1024) NOT NULL,
  `status` TINYINT UNSIGNED NOT NULL,
  `consultation_format` TINYINT UNSIGNED NOT NULL,
  `consultation_method` TINYINT UNSIGNED NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `categories_plans_idx` (`category_id` ASC) VISIBLE,
  INDEX `users_plans_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `categories_plans`
    FOREIGN KEY (`category_id`)
    REFERENCES `sql_test`.`categories` (`id`),
  CONSTRAINT `users_plans`
    FOREIGN KEY (`user_id`)
    REFERENCES `sql_test`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sql_test`.`contract_requests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql_test`.`contract_requests` (
  `id` CHAR(36) NOT NULL,
  `message` VARCHAR(500) NOT NULL,
  `plan_id` CHAR(36) NOT NULL,
  `contract_amount` MEDIUMINT UNSIGNED NOT NULL DEFAULT '1000',
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Plans_Contract_requests` (`plan_id` ASC) VISIBLE,
  CONSTRAINT `fk_Plans_Contract_requests`
    FOREIGN KEY (`plan_id`)
    REFERENCES `sql_test`.`plans` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sql_test`.`contracts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql_test`.`contracts` (
  `id` CHAR(36) NOT NULL,
  `contract_request_id` CHAR(36) NOT NULL,
  `approval_message` VARCHAR(500) NOT NULL DEFAULT 'こちらに承認メッセージを500文字以内で入力して下さい',
  `created_at` DATETIME NOT NULL,
  INDEX `contract_requests_contracts_idx` (`contract_request_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `contract_requests_contracts`
    FOREIGN KEY (`contract_request_id`)
    REFERENCES `sql_test`.`contract_requests` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sql_test`.`mentor_recruitments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql_test`.`mentor_recruitments` (
  `id` CHAR(36) NOT NULL,
  `title` VARCHAR(512) NOT NULL,
  `category_id` CHAR(36) NOT NULL,
  `budget_from` MEDIUMINT UNSIGNED NOT NULL DEFAULT '1000',
  `budget_to` MEDIUMINT UNSIGNED NOT NULL DEFAULT '1000',
  `application_period_from` DATE NOT NULL,
  `application_period_to` DATE NOT NULL,
  `consultation_format` TINYINT UNSIGNED NOT NULL,
  `consultation_method` TINYINT UNSIGNED NOT NULL,
  `description` VARCHAR(2000) NOT NULL DEFAULT 'こちらに内容を２０００字以内で記入してください',
  `status` TINYINT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sql_test`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql_test`.`tags` (
  `id` CHAR(36) NOT NULL,
  `name` VARCHAR(25) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sql_test`.`mentor_recruitments_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql_test`.`mentor_recruitments_tags` (
  `id` CHAR(36) NOT NULL,
  `mentor_recruitment_id` CHAR(36) NOT NULL,
  `tag_id` CHAR(36) NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  INDEX `tags_mentor_recruitments_tags_idx` (`tag_id` ASC) VISIBLE,
  CONSTRAINT `mentor_recruitments_tags_mentor_recruitments`
    FOREIGN KEY (`mentor_recruitment_id`)
    REFERENCES `sql_test`.`mentor_recruitments` (`id`),
  CONSTRAINT `tags_mentor_recruitments_tags`
    FOREIGN KEY (`tag_id`)
    REFERENCES `sql_test`.`tags` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;



-- -----------------------------------------------------
-- Table `sql_test`.`plans_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql_test`.`plans_tags` (
  `plan_id` CHAR(36) NOT NULL,
  `tag_id` CHAR(36) NOT NULL,
  `created_at` DATETIME NOT NULL,
  PRIMARY KEY (`plan_id`, `tag_id`),
  INDEX `fk_tags_plansTags_idx` (`tag_id` ASC) VISIBLE,
  CONSTRAINT `fk_plansTags_plans`
    FOREIGN KEY (`plan_id`)
    REFERENCES `sql_test`.`plans` (`id`),
  CONSTRAINT `fk_tags_plansTags`
    FOREIGN KEY (`tag_id`)
    REFERENCES `sql_test`.`tags` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sql_test`.`proposals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql_test`.`proposals` (
  `id` CHAR(36) NOT NULL,
  `users_id` CHAR(36) NOT NULL,
  `mentor_recruitment_id` CHAR(36) NOT NULL,
  `content` VARCHAR(2000) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Users_Proposals_idx` (`users_id` ASC) VISIBLE,
  INDEX `mentor_recruitment_proposalsID` (`mentor_recruitment_id` ASC) VISIBLE,
  CONSTRAINT `fk_Users_Proposals`
    FOREIGN KEY (`users_id`)
    REFERENCES `sql_test`.`users` (`id`),
  CONSTRAINT `mentor_recruitment_proposalsID`
    FOREIGN KEY (`mentor_recruitment_id`)
    REFERENCES `sql_test`.`mentor_recruitments` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sql_test`.`skills`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sql_test`.`skills` (
  `id` CHAR(36) NOT NULL,
  `tag_id` CHAR(36) NOT NULL,
  `user_id` CHAR(36) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NOT NULL,
  `evaluation` TINYINT UNSIGNED NOT NULL,
  `years` TINYINT UNSIGNED NOT NULL,
  UNIQUE INDEX `tag_id_user_id_UNIQUE` (`user_id` ASC, `tag_id` ASC) VISIBLE,
  INDEX `fk_users_skills_idx` (`user_id` ASC) INVISIBLE,
  INDEX `fk_Tags_Skills` (`tag_id` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_Tags_Skills`
    FOREIGN KEY (`tag_id`)
    REFERENCES `sql_test`.`tags` (`id`),
  CONSTRAINT `fk_users_skills`
    FOREIGN KEY (`user_id`)
    REFERENCES `sql_test`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
