version: "3.2"
services:
  mysql_test:
    build: .
    restart: always
    environment: 
      MYSQL_DATABASE: mydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "9999:3306"
    volumes:
      - "db-data:/var/lib/mysql"
    networks:
      - db_network
  
volumes:
  db-data:

networks:
  db_network:
    driver: bridge